// Realistic seeded demo data, used only when VITE_SUPABASE_URL /
// VITE_SUPABASE_ANON_KEY aren't configured (see supabase.ts). Shapes match
// the real schema exactly so swapping to live data changes nothing else.

import type {
  ApprovalRequest,
  ComplianceQuestion,
  ComplianceRequest,
  ConnectorConfig,
  PlaybookRun,
  RemediationAction,
  SecurityFinding,
} from "./types";

const ORG = "demo-org-0000-0000-0000-000000000000";
const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => hoursAgo(d * 24);

export const MOCK_FINDINGS: SecurityFinding[] = [
  {
    id: "f1",
    organization_id: ORG,
    connector: "github-security",
    resource_ref: "github.com/acme-corp/payments-api",
    finding_type: "secret_scanning.exposed_credential",
    severity: "critical",
    status: "investigating",
    summary: "Committed AWS access key detected in payments-api commit history",
    evidence: {},
    related_node_ids: [],
    detected_at: hoursAgo(2),
    updated_at: hoursAgo(1),
  },
  {
    id: "f2",
    organization_id: ORG,
    connector: "crowdstrike-falcon",
    resource_ref: "falcon-host/prod-web-07",
    finding_type: "edr.suspicious_process_injection",
    severity: "critical",
    status: "open",
    summary: "Process injection technique detected on prod-web-07",
    evidence: {},
    related_node_ids: [],
    detected_at: hoursAgo(4),
    updated_at: hoursAgo(4),
  },
  {
    id: "f3",
    organization_id: ORG,
    connector: "aws-security-hub",
    resource_ref: "arn:aws:s3:::acme-reports-bucket",
    finding_type: "s3.public_bucket",
    severity: "high",
    status: "open",
    summary: "S3 bucket acme-reports-bucket is publicly readable",
    evidence: {},
    related_node_ids: [],
    detected_at: hoursAgo(9),
    updated_at: hoursAgo(9),
  },
  {
    id: "f4",
    organization_id: ORG,
    connector: "microsoft-sentinel",
    resource_ref: "user/jtorres@acme-corp.com",
    finding_type: "sentinel.impossible_travel_signin",
    severity: "high",
    status: "investigating",
    summary: "Sign-in from Lagos and Warsaw within an implausible time window",
    evidence: {},
    related_node_ids: [],
    detected_at: hoursAgo(14),
    updated_at: hoursAgo(6),
  },
  {
    id: "f5",
    organization_id: ORG,
    connector: "tenable-io",
    resource_ref: "tenable-asset/db-primary-02",
    finding_type: "vuln.unpatched_cve",
    severity: "high",
    status: "open",
    summary: "CVE-2025-21412 (known exploit) unpatched on db-primary-02",
    evidence: {},
    related_node_ids: [],
    detected_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "f6",
    organization_id: ORG,
    connector: "aws-security-hub",
    resource_ref: "arn:aws:iam::412:role/legacy-ci-deploy",
    finding_type: "iam.unused_access_key",
    severity: "medium",
    status: "open",
    summary: "IAM access key unused for 112 days (dormancy threshold: 90d)",
    evidence: {},
    related_node_ids: [],
    detected_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "f7",
    organization_id: ORG,
    connector: "github-security",
    resource_ref: "github.com/acme-corp/internal-tools",
    finding_type: "dependabot.vulnerable_dependency",
    severity: "medium",
    status: "remediated",
    summary: "lodash 4.17.15 has a known prototype pollution vulnerability",
    evidence: {},
    related_node_ids: [],
    detected_at: daysAgo(5),
    updated_at: daysAgo(3),
  },
  {
    id: "f8",
    organization_id: ORG,
    connector: "tenable-io",
    resource_ref: "tenable-asset/web-staging-03",
    finding_type: "vuln.outdated_tls",
    severity: "low",
    status: "accepted_risk",
    summary: "TLS 1.1 still enabled on staging load balancer",
    evidence: {},
    related_node_ids: [],
    detected_at: daysAgo(9),
    updated_at: daysAgo(4),
  },
];

export const MOCK_REMEDIATIONS: RemediationAction[] = [
  {
    id: "r1",
    organization_id: ORG,
    finding_id: "f1",
    action_type: "rotate_secret",
    description: "Rotate credential exposed at github.com/acme-corp/payments-api",
    status: "pending_approval",
    auto_approved: false,
    requested_by: null,
    approved_by: null,
    executed_at: null,
    failure_reason: null,
    created_at: hoursAgo(2),
  },
  {
    id: "r2",
    organization_id: ORG,
    finding_id: "f2",
    action_type: "isolate_endpoint",
    description: "Isolate falcon-host/prod-web-07 pending investigation",
    status: "pending_approval",
    auto_approved: false,
    requested_by: null,
    approved_by: null,
    executed_at: null,
    failure_reason: null,
    created_at: hoursAgo(4),
  },
  {
    id: "r3",
    organization_id: ORG,
    finding_id: "f6",
    action_type: "revoke_access",
    description: "Revoke unused IAM access key legacy-ci-deploy",
    status: "proposed",
    auto_approved: false,
    requested_by: null,
    approved_by: null,
    executed_at: null,
    failure_reason: null,
    created_at: daysAgo(2),
  },
  {
    id: "r4",
    organization_id: ORG,
    finding_id: "f7",
    action_type: "open_ticket",
    description: "Patch SLA breach risk for lodash dependency",
    status: "executed",
    auto_approved: true,
    requested_by: null,
    approved_by: null,
    executed_at: daysAgo(3),
    failure_reason: null,
    created_at: daysAgo(5),
  },
];

export const MOCK_APPROVALS: ApprovalRequest[] = [
  {
    id: "a1",
    organization_id: ORG,
    ref_type: "remediation_action",
    ref_id: "r1",
    requested_by: null,
    eligible_approver_ids: [],
    status: "pending",
    locked_by: null,
    locked_at: null,
    resolved_by: null,
    resolved_at: null,
    channel_ref: null,
    created_at: hoursAgo(2),
  },
  {
    id: "a2",
    organization_id: ORG,
    ref_type: "remediation_action",
    ref_id: "r2",
    requested_by: null,
    eligible_approver_ids: [],
    status: "pending",
    locked_by: null,
    locked_at: null,
    resolved_by: null,
    resolved_at: null,
    channel_ref: null,
    created_at: hoursAgo(4),
  },
  {
    id: "a3",
    organization_id: ORG,
    ref_type: "compliance_answer",
    ref_id: "q1",
    requested_by: null,
    eligible_approver_ids: [],
    status: "pending",
    locked_by: null,
    locked_at: null,
    resolved_by: null,
    resolved_at: null,
    channel_ref: null,
    created_at: hoursAgo(10),
  },
];

export const MOCK_COMPLIANCE_REQUESTS: ComplianceRequest[] = [
  {
    id: "cr1",
    organization_id: ORG,
    request_type: "security_questionnaire",
    source: "acme-customer-procurement@bigbank.com",
    title: "BigBank Vendor Security Questionnaire",
    status: "pending_review",
    due_date: new Date(now + 4 * 86_400_000).toISOString().slice(0, 10),
    created_by: null,
    created_at: daysAgo(1),
    updated_at: hoursAgo(10),
  },
  {
    id: "cr2",
    organization_id: ORG,
    request_type: "rfp",
    source: null,
    title: "RFP: Northwind Logistics",
    status: "in_progress",
    due_date: new Date(now + 10 * 86_400_000).toISOString().slice(0, 10),
    created_by: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: "cr3",
    organization_id: ORG,
    request_type: "governance_review",
    source: "soc2-gap-analysis",
    title: "SOC2 gap analysis — 3 unmapped control(s)",
    status: "intake",
    due_date: null,
    created_by: null,
    created_at: hoursAgo(18),
    updated_at: hoursAgo(18),
  },
  {
    id: "cr4",
    organization_id: ORG,
    request_type: "internal_audit",
    source: null,
    title: "Control test: Encryption at rest",
    status: "completed",
    due_date: null,
    created_by: null,
    created_at: daysAgo(6),
    updated_at: daysAgo(6),
  },
];

export const MOCK_COMPLIANCE_QUESTIONS: ComplianceQuestion[] = [
  {
    id: "q1",
    request_id: "cr1",
    organization_id: ORG,
    question_text: "Do you encrypt customer data at rest?",
    answer_text:
      "Yes. All customer data at rest is encrypted using AES-256 [1], enforced via our cloud infrastructure encryption policy [2].",
    evidence_node_ids: ["e1", "e2"],
    confidence: 0.8,
    flagged_gap: false,
    gap_reason: null,
    answered_at: hoursAgo(10),
    created_at: daysAgo(1),
  },
  {
    id: "q2",
    request_id: "cr1",
    organization_id: ORG,
    question_text: "Do you maintain a current SOC 2 Type II report?",
    answer_text: null,
    evidence_node_ids: [],
    confidence: 0,
    flagged_gap: true,
    gap_reason: "No evidence found in the graph for this question.",
    answered_at: hoursAgo(10),
    created_at: daysAgo(1),
  },
  {
    id: "q3",
    request_id: "cr2",
    organization_id: ORG,
    question_text: "Describe your incident response process.",
    answer_text:
      "Our incident response plan [1] defines a 4-hour acknowledgement SLA and escalation chain reviewed quarterly.",
    evidence_node_ids: ["e3"],
    confidence: 0.8,
    flagged_gap: false,
    gap_reason: null,
    answered_at: daysAgo(1),
    created_at: daysAgo(3),
  },
];

export const MOCK_CONNECTORS: ConnectorConfig[] = [
  {
    id: "c1",
    organization_id: ORG,
    connector_type: "aws-security-hub",
    enabled: true,
    credential_ref: "vault:aws-sec-hub-demo",
    config: {},
    last_sync_at: hoursAgo(1),
    created_at: daysAgo(30),
    updated_at: hoursAgo(1),
  },
  {
    id: "c2",
    organization_id: ORG,
    connector_type: "github-security",
    enabled: true,
    credential_ref: "vault:github-app-demo",
    config: {},
    last_sync_at: hoursAgo(2),
    created_at: daysAgo(30),
    updated_at: hoursAgo(2),
  },
  {
    id: "c3",
    organization_id: ORG,
    connector_type: "microsoft-sentinel",
    enabled: true,
    credential_ref: null,
    config: {},
    last_sync_at: hoursAgo(14),
    created_at: daysAgo(12),
    updated_at: hoursAgo(14),
  },
  {
    id: "c4",
    organization_id: ORG,
    connector_type: "crowdstrike-falcon",
    enabled: true,
    credential_ref: "vault:falcon-demo",
    config: {},
    last_sync_at: hoursAgo(4),
    created_at: daysAgo(12),
    updated_at: hoursAgo(4),
  },
  {
    id: "c5",
    organization_id: ORG,
    connector_type: "tenable-io",
    enabled: false,
    credential_ref: null,
    config: {},
    last_sync_at: null,
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
  },
  {
    id: "c6",
    organization_id: ORG,
    connector_type: "siem-webhook",
    enabled: false,
    credential_ref: null,
    config: {},
    last_sync_at: null,
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
  },
];

export const MOCK_PLAYBOOK_RUNS: PlaybookRun[] = [
  {
    id: "pr1",
    organization_id: ORG,
    playbook_id: "cloud-misconfiguration-sweep",
    category: "cybersecurity",
    status: "completed",
    summary: "2 cloud misconfiguration finding(s) recorded.",
    data: {},
    findings_created: 2,
    gaps_flagged: 0,
    triggered_by: null,
    started_at: hoursAgo(1),
    finished_at: hoursAgo(1),
  },
  {
    id: "pr2",
    organization_id: ORG,
    playbook_id: "soc2-evidence-freshness-sweep",
    category: "compliance",
    status: "completed",
    summary: "4 stale evidence node(s) found; 2 auto-refreshed, 2 escalated to owners.",
    data: {},
    findings_created: 0,
    gaps_flagged: 2,
    triggered_by: null,
    started_at: hoursAgo(6),
    finished_at: hoursAgo(6),
  },
  {
    id: "pr3",
    organization_id: ORG,
    playbook_id: "dormant-privileged-access",
    category: "cybersecurity",
    status: "completed",
    summary: "Reviewed 2 identity connector(s); 1 dormant privileged access finding(s) created.",
    data: {},
    findings_created: 1,
    gaps_flagged: 0,
    triggered_by: null,
    started_at: daysAgo(2),
    finished_at: daysAgo(2),
  },
  {
    id: "pr4",
    organization_id: ORG,
    playbook_id: "policy-framework-gap-analysis",
    category: "compliance",
    status: "completed",
    summary: "SOC2: 13/16 controls have matching evidence; 3 gap(s) logged.",
    data: {},
    findings_created: 0,
    gaps_flagged: 3,
    triggered_by: null,
    started_at: hoursAgo(18),
    finished_at: hoursAgo(18),
  },
  {
    id: "pr5",
    organization_id: ORG,
    playbook_id: "vulnerability-prioritization",
    category: "cybersecurity",
    status: "failed",
    summary: "tenable-io is not enabled for this org (see /cyber connectors).",
    data: {},
    findings_created: 0,
    gaps_flagged: 0,
    triggered_by: null,
    started_at: daysAgo(1),
    finished_at: daysAgo(1),
  },
];

export function severityBreakdown(findings: SecurityFinding[]) {
  const open = findings.filter((f) => f.status === "open" || f.status === "investigating");
  const counts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of open) counts[f.severity]++;
  return counts;
}

// 14-day synthetic trend for the overview chart, weighted toward the mock findings above.
export function findingsTrend() {
  const days = 14;
  return Array.from({ length: days }, (_, i) => {
    const dayIndex = days - 1 - i;
    const base = 1 + Math.round(Math.sin(dayIndex / 2.3) * 1.5 + 2);
    return {
      date: new Date(now - dayIndex * 86_400_000).toLocaleDateString(undefined, {
        month: "short",
        day: "numeric",
      }),
      critical: Math.max(0, Math.round(base * 0.3 + (dayIndex === 0 ? 2 : 0))),
      high: Math.max(0, Math.round(base * 0.5)),
      medium: Math.max(0, Math.round(base * 0.8)),
      low: Math.max(0, Math.round(base * 0.4)),
    };
  });
}
